= coderadar Administration Guide
v{version}, {date}
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:

[introduction]
== Introduction

This guide is intended for administrators and developers who want to get a Coderadar server up and running.

== Getting coderadar up and running
A Coderadar distribution contains a JAR file and a properties
file that contains the default configuration.

=== Configuration Parameters

Coderadar can be configured by adjusting the parameters in the application.properties file (either before jar-packaging or by supplying the file alongside the jar).

==== Configuring the scan interval

`coderadar.scanIntervalInSeconds=30`

Adjusting this value will change how often projects are checked for new commits/branches.

==== Configuring the working directory

This is the directory projects will be cloned to. It's path can be adjusted by changing the following property:

`coderadar.workdir=coderadar-workdir`

==== Configuring the access/refresh token validity duration

The following properties control how long a access/refresh token is valid:

`coderadar.authentication.accessToken.durationInMinutes=15`
`coderadar.authentication.refreshToken.durationInMinutes=86400`

==== Configuring authentication

Authentication can be enabled or disabled with the following property:

`coderadar.authentication.enabled=true`

==== Configuring CORS

CORS can be enabled or disabled with the following property:

`coderadar.cors.enabled=true`

==== Configuring logging levels

The logging levels can be adjusting with the following properties:

`logging.level.io.reflectoring.coderadar=DEBUG`
`logging.level.org.reflections=ERROR`

==== Configuring the log file

The log file's path can be adjusted with the following property:

`logging.file=coderadar.log`

==== Configuring the database connection

Coderadar works with Neo4j version 3.5.* and requires the APOC plugin to be installed.
The easiest way to quickly configure a local Neo4j instance is by using Neo4j Desktop.

The credentials for the Neo4j database instance can be configured with the following properties:

`spring.data.neo4j.username=neo4j`
`spring.data.neo4j.password=neo3j`

=== Starting Coderadar

Starting Coderadar requires a running Neo4j instance on port 7687.
Once started, the Coderadar REST-API will be available on port 8080.
If the jar contains the coderadar UI, it will also be available on port 8080.
For more information on it, have a look at the REST-API documentation:

https://adessoag.github.io/coderadar/current/docs/restapi.html

=== Starting the Coderadar UI

To start the Coderadar UI, you have to build it first. This requires having NPM installed, going to the `coderadar-ui` directory and
installing the dependencies by running `npm install` and running the UI-server with `npm start`.
The UI will be available on port 4200.

=== Coderadar system requirements

For comfortable development, Coderadar itself requires about 5GB of System memory. Note that this largely depends on how large
the projects you're working with are and how many of them are. In order to save and analyze very large projects, Neo4j should be configured with at least 10GB of available heap memeory.
