= coderadar REST API
v{version}, {date}
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:

[introduction]
== Introduction

// TODO schreibweise von coderadar-Begriffen (Project, FilePattern, Module, ..) und Fachbegriffen (refresh token, ..)

coderadar server is a tool for continuous source code analysis. This document describes the REST API of coderadar.
The REST API may for example be accessed by the following clients:

* applications that provide a user interface for coderadar (like coderadar's own user interface)
* third-party applications or tools that want to integrate data provided by coderadar

This guide is aimed at developers of such applications.

=== Usage of HTTP Verbs

The following table describes how the coderadar API interprets the HTTP verbs.

.HTTP Verbs
|===
|HTTP Verb | Usage

|GET
|GET is used to retrieve information.

|POST
|POST is used to create and update resources.

|DELETE
|DELETE is used to delete resources.

|PUT
|PUT is not used at this time.

|PATCH
|PATCH is not used at this time.
|===

anchor:usage-of-get[]
[NOTE]
=====
.Usage of GET
If a GET request requires parameters, they can usually be
provided as parameters encoded in the URL. However, in some cases parameters are too unwieldy to
encode them in the URL. In these cases the parameters are expected as JSON string within the request
body. Since some tools don't allow GET requests with a body, coderadar accepts the POST method in
these cases as well.
=====

=== Error Handling

==== Successful Requests

Successful requests return a response with HTTP status 200 (OK) or 201 (CREATED) and contain a JSON structure in the response
body if applicable.

==== Validation Errors

POST requests against the coderadar API usually expect a JSON structure in the request body. If the JSON structure
contains values that are invalid, the API returns a response with HTTP status 400 (bad request) that contains
an error JSON structure object that looks like this:

include::{snippets}/projects/create/error400/http-response.adoc[]

==== General Errors

If some unexpected error occurs during the processing of a request, the API returns a response with HTTP status 500
(internal server error).

== User Management
anchor:chapter-configure[]
This section describes the REST endpoints for managing coderadar users.

=== Users
To access the functionality of coderadar you have to register a user.
You need to define a username and a password. The password will be sent as
plain text and hashed on server side for persisting.

==== Registering a User

===== Registration Data Structure
include::{snippets}/user/registration/request-fields.adoc[]

===== Example Request

include::{snippets}/user/registration/http-request.adoc[]

===== Example Response

include::{snippets}/user/registration/http-response.adoc[]

==== Loading a User

===== Example Request

include::{snippets}/users/get/http-request.adoc[]

===== Example Response

include::{snippets}/users/get/http-response.adoc[]

==== Login
anchor:login[]
A user has to log in to use other endpoints of coderadar.
If the log in is successful, user obtains two JSON Web Tokens https://jwt.io

* an access token
* a refresh token.

How to use the tokens is described in <<authentication, Authentication>>

===== Login Data Structure
include::{snippets}/user/auth/request-fields.adoc[]

===== Example Request
include::{snippets}/user/auth/http-request.adoc[]

===== Example Response
include::{snippets}/user/auth/http-response.adoc[]

==== Token Refresh
anchor:refresh[]
To get a new access token after the current token has been expired you have
to use the refresh token you got after successful login

===== Login Data Structure
include::{snippets}/user/refresh/request-fields.adoc[]

===== Example Request
include::{snippets}/user/refresh/http-request.adoc[]

===== Example Response
include::{snippets}/user/refresh/http-response.adoc[]

==== Password Change
To change the password user has to be authenticated by the access token
and has to send a new password and thе refresh token to the server. The user will be found by the
refresh token and his refresh tokens will be revoked so the user has to log in with the username and password
again after the current access token is expired.

===== Login Data Structure
include::{snippets}/user/password/change/request-fields.adoc[]

===== Example Request
include::{snippets}/user/password/change/http-request.adoc[]

===== Example Response
include::{snippets}/user/password/change/http-response.adoc[]

anchor:authentication[]

==== Authentication
After a user registered, he or she can start working with coderadar.
The first step is login. To log in in coderadar use the <<login, Login>> endpoint. The user must use the username and the password
specified at registration. If the login was successful user gets two JSON Web Tokens (see https://jwt.io):

* an access token and
* a refresh token.

After that the user has to use the access token for authentication with each request to a protected route or resource.
The tokens are signed by the server so the server can validate the signature of the token to grant the access to resources.
The access token is a Base64 encoded String, that must be added to Authorization HTTP header like this:

 Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2RlcmFkYXIiLCJleHAiOjE0ODQ1MTUzOTUsInR5cGUiOiJSRUZSRVNIIiwiaWF0IjoxNDg0NTE1NDU1LCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJyYWRhciJ9.zfkyc5jkPiAUEt7nU25SJxKprcPiXaiq0Q6bCJ_RrQo

The access token is short-lived and by default expires after 15 minutes.
When the access token expires, the user has to require a new access token. It can be done with the refresh token
user got as response after login. The refresh token must be sent with a request to the <<refresh, Token Refresh>> endpoint.
The refresh token is long-lived and by default expires after 60 days.
When the refresh token expired or was revoked for example after a password change,
a user has to login again to get a new refresh token.

A typical work flow looks like this:

. Client logs in with username and password and gets two tokens
. Client requires resources using the access token in each request
. After 15 minutes client gets a 401-Response
. Clients tries to get a new access token using refresh token
. Clients gets a new acess token and can request further resources
. If the client can't get a new access token using the refresh token, client has to login again with username and password.

See more: https://auth0.com/docs/tokens/refresh-token and https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/


== Configuring a Project
anchor:chapter-configure[]

This section describes the resources you can interact with to configure a project to be analyzed by coderadar.
To run an analysis on a project, you have to at least follow these steps:

. <<creating-a-project, Create a Project>> so that coderadar knows where to get the code base. Once this step
  is done, coderadar will clone the repository and create some metadata on the commits and code base. Depending
  on the size of the project, it may take a while to complete.
. <<setting-filepatterns, Define File Patterns>> to tell coderadar which files should be analyzed. If this step
  is omitted, an analysis will provide no results.
. <<create-analyzer, Add at least one analyzer>> to your project. Each added analyzer will run over the
  files specified in the previous step and provide some code metrics.
. <<start-analysis, Start an Analyzing Job>> for your project. coderadar will start to analyze all files
  in the commits between startDate and endDate using the analyzers you have configured. Depending on the size
  of the code base and the number of configured analyzers, this may take some time to finish.

=== Project

A project defines some metadata about the project you want coderadar to analyze. With a project resource
and its sub-resources you provide coderadar with the information it needs to analyze the source code.

==== Structure

include::{snippets}/projects/create/request-fields.adoc[]

==== Creating a Project
anchor:creating-a-project[]

// TODO dates have Null as data type

===== Example Request

include::{snippets}/projects/create/http-request.adoc[]

===== Example Response

include::{snippets}/projects/create/http-response.adoc[]

==== Listing Projects

===== Example Request

include::{snippets}/projects/list/http-request.adoc[]

===== Example Response

include::{snippets}/projects/list/http-response.adoc[]


==== Updating a Project

===== Example Request

include::{snippets}/projects/update/http-request.adoc[]

===== Example Response

include::{snippets}/projects/update/http-response.adoc[]

==== Get a Project

===== Example Request

include::{snippets}/projects/get/http-request.adoc[]

===== Example Response

include::{snippets}/projects/get/http-response.adoc[]

==== Deleting a Project

===== Example Request

include::{snippets}/projects/delete/http-request.adoc[]

===== Example Response

include::{snippets}/projects/delete/http-response.adoc[]

=== Modules
anchor:chapter-modules[]
Source code is usually arranged within multiple modules that each contains a set of source files.
Using the following REST endpoints, you can provide coderadar with information about the modules within
your codebase. Each module simply is a path into the VCS codebase. All files that are within that path
are considered to be part of the module.

Please note that the operations to create, update and delete modules may take some time to be finished since all
files in all commits have to be updated during these operations.

==== Structure

include::{snippets}/modules/create/request-fields.adoc[]

==== Creating a Module

===== Example Request

include::{snippets}/modules/create/http-request.adoc[]

===== Example Response

include::{snippets}/modules/create/http-response.adoc[]

==== Get a Module of a Project

===== Example Request

include::{snippets}/modules/get/http-request.adoc[]

===== Example Response

include::{snippets}/modules/get/http-response.adoc[]

==== Listing all Modules of a Project

===== Example Request

include::{snippets}/modules/list/http-request.adoc[]

===== Example Response

include::{snippets}/modules/list/http-response.adoc[]

==== Deleting a Module

===== Example Request

include::{snippets}/modules/delete/http-request.adoc[]

===== Example Response

include::{snippets}/modules/delete/http-response.adoc[]

=== Branches

==== Listing Branches

===== Example Request

include::{snippets}/branches/list/http-request.adoc[]

===== Example Response

include::{snippets}/branches/list/http-response.adoc[]

=== File Patterns

A File Pattern describes a set of files within a Project's code base. Each project can have several file patterns
defined. File Patterns may either define a pattern for files to be INCLUDED or files to be EXCLUDED.

If a project has no File Patterns defined, the analysis won't start.

==== Structure

include::{snippets}/filepatterns/create-update/request-fields.adoc[]

==== Listing a Project's File Patterns

===== Example Request

include::{snippets}/filepatterns/list/http-request.adoc[]

===== Example Response

include::{snippets}/filepatterns/list/http-response.adoc[]

==== Adding a File Pattern to a Project
anchor:setting-filepatterns[]

===== Example Request

include::{snippets}/filepatterns/create-update/http-request.adoc[]

===== Example Response

include::{snippets}/filepatterns/create-update/http-response.adoc[]

==== Removing a File Pattern from a Project

===== Example Request

include::{snippets}/filepatterns/delete/http-request.adoc[]

===== Example Response

include::{snippets}/filepatterns/delete/http-response.adoc[]

==== Get a specific File Pattern from a Project

===== Example Request

include::{snippets}/filepatterns/get/http-request.adoc[]

===== Example Response

include::{snippets}/filepatterns/get/http-response.adoc[]

==== Update a File Pattern for a Project

===== Example Request

include::{snippets}/filepatterns/create-update/http-request.adoc[]

===== Example Response

include::{snippets}/filepatterns/create-update/http-response.adoc[]

=== Analyzer Configuration

Coderadar has a plugin system for source code analyzers so you can implement your own analyzers that produce the metrics
you need (or you can use the analyzer plugins that are shipped with coderadar). For each project, you can configure each analyzer
plugin via the AnalyzerConfiguration resource.

==== Structure

include::{snippets}/analyzerConfiguration/post/request-fields.adoc[]

==== Adding an Analyzer Configuration
anchor:create-analyzer[]

===== Example Request

include::{snippets}/analyzerConfiguration/post/http-request.adoc[]

===== Example Response

include::{snippets}/analyzerConfiguration/post/http-response.adoc[]

==== Deleting an Analyzer Configuration

===== Example Request

include::{snippets}/analyzerConfiguration/delete/http-request.adoc[]

===== Example Response

include::{snippets}/analyzerConfiguration/delete/http-response.adoc[]

==== Updating an Analyzer Configuration

===== Example Request

include::{snippets}/analyzerConfiguration/update/http-request.adoc[]

===== Example Response

include::{snippets}/analyzerConfiguration/update/http-response.adoc[]

==== Listing a Project's Analyzer Configurations

===== Example Request

include::{snippets}/analyzerConfiguration/get/http-request.adoc[]

===== Example Response

include::{snippets}/analyzerConfiguration/get/http-response.adoc[]

==== Loading a single Analyzer Configuration

===== Example Request

include::{snippets}/analyzerConfiguration/getSingle/http-request.adoc[]

===== Example Response

include::{snippets}/analyzerConfiguration/getSingle/http-response.adoc[]

=== Analyzing

An analysis can be started for a project in coderadar. By default a Project's codebase is not analyzed.
To analyze the codebase an analysis has to be triggered.

==== Starting an Analysis
anchor:start-analysis[]

===== Example Request

The request body consist of a list of branch names and can be empty. In that case
all branches are analyzed.

include::{snippets}/analysis/start/http-request.adoc[]

===== Example Response

include::{snippets}/analysis/start/http-response.adoc[]

==== Retrieving an Analysis status

===== Example Request

include::{snippets}/analysis/status/http-request.adoc[]

===== Example Response

include::{snippets}/analysis/status/http-response.adoc[]

==== Resetting an Analysis/Deleting Analysis results

===== Example Request

include::{snippets}/analysis/reset/http-request.adoc[]

===== Example Response

include::{snippets}/analysis/reset/http-response.adoc[]

== Querying Global Data
anchor:chapter-query-global-data[]

This section describes the resources that are not attached to a project and are thus available server-wide.

=== Analyzer

coderadar can be configured to use Analyzer plugins that analyze source code to create certain metrics.

==== Listing available Analyzers

===== Example Request

include::{snippets}/analyzer/list/http-request.adoc[]

===== Example Response

include::{snippets}/analyzer/list/http-response.adoc[]

== Querying Project Data
anchor:chapter-query-project-data[]

This section describes the resources that are attached to a project and are only available in the context of a
project.

=== Metric

The Metric resource describes a metric that an analyzer configured in your project provides.

==== Listing available Metrics

You can list all metrics that have been measured for your project by calling the request below.

[NOTE]
=====
Metric values will become available as soon as an <<start-analysis,analysis>> starts for your project.
At that moment, analysis of each commit in the date range starts The date range is set in the project
settings. The project will only be regarded in this date range. Depending on how many commits that are and how
many analyzers are configured, analysis will take a while.
=====

===== Example Request

include::{snippets}/metrics/list/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/list/http-response.adoc[]

=== Commit

The Commit resource contains some metadata about a commit to your project's version control system. Commits
will become available as soon as you have created a project and provided valid VCS credentials (see <<creating-a-project,Creating a Project>>).
Depending of the number of commits you have in your project, it may take a while until all commits
are available.

==== Structure
include::{snippets}/commit/list/response-fields.adoc[]

==== Listing a Project's Commits

===== Example Request

include::{snippets}/commit/list/http-request.adoc[]

===== Example Response

include::{snippets}/commit/list/http-response.adoc[]

==== Listing commits for a given contributor

An additional email parameter may be supplied to this request to only return the commits authored by the matching contributor.

===== Example Request

include::{snippets}/commit/list/email/http-request.adoc[]

===== Example Response

include::{snippets}/commit/list/email/http-response.adoc[]


==== Listing a Project's Commits as a Git log

===== Response Structure

include::{snippets}/commit/log/response-fields.adoc[]

===== Example Request

include::{snippets}/commit/log/http-request.adoc[]

===== Example Response

include::{snippets}/commit/log/http-response.adoc[]

=== Commit Metric Values

You can access the metric values aggregated for each commit using this operation. You have to specify a query object
that defines which metrics you are interested in.

[NOTE]
=====
Metric values will become available as soon as an <<start-analysis,Analyzing Job>> starts for your project.
At that moment, analysis of each commit defined in the job starts. Depending on how many commits that are and how
many analyzers are configured, analysis will take a while.
=====

==== Querying Metric Values of a Commit

===== Query Structure

include::{snippets}/metrics/commit/metrics/request-fields.adoc[]

===== Example Request

[NOTE]
=====
This request can be sent using either the GET or the POST method. See <<usage-of-get, Usage of GET>>.
=====
include::{snippets}/metrics/commit/metrics/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/commit/metrics/http-response.adoc[]

==== Querying File content, metric values and findings of a file in a commit.

===== Request Structure

include::{snippets}/files/content/request-fields.adoc[]

===== Response Structure

include::{snippets}/files/content/response-fields.adoc[]

===== Example Request

[NOTE]
=====
This request can be sent using either the GET or the POST method. See <<usage-of-get, Usage of GET>>.

=====
include::{snippets}/files/content/http-request.adoc[]

===== Example Response

include::{snippets}/files/content/http-response.adoc[]

==== Querying the file diff against the same file in the first commit parent.

===== Request Structure

include::{snippets}/files/diff/request-fields.adoc[]

===== Response Structure

include::{snippets}/files/diff/response-fields.adoc[]

===== Example Request

[NOTE]
=====
This request can be sent using either the GET or the POST method. See <<usage-of-get, Usage of GET>>.

=====
include::{snippets}/files/diff/http-request.adoc[]

===== Example Response

include::{snippets}/files/diff/http-response.adoc[]

=== Metrics Trees

==== Querying Metrics for all Files in a Single Commit
This endpoint provides a tree structure containing metrics for all modules and files of the project at the
time of a specified commit.

===== Request Structure

include::{snippets}/metrics/tree/request-fields.adoc[]

===== Response Structure

include::{snippets}/metrics/tree/response-fields.adoc[]

===== Example Request

[NOTE]
=====
This request can be sent using either the GET or the POST method. See <<usage-of-get, Usage of GET>>.
=====
include::{snippets}/metrics/tree/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/tree/http-response.adoc[]

==== Querying Metrics for all Files in two Commits
This endpoint provides a tree structure containing metrics for all modules and files of the project at the
time of two specified commits so the metric values between these commits can be directly compared.
Also, the tree contains information about files that have been renamed or moved between the two specified
commits.

===== Request Structure

include::{snippets}/metrics/deltaTree/request-fields.adoc[]

===== Response Structure
// TODO renamedFrom, renamedTo, changes without data type; renamedFrom, renamedTo without description

include::{snippets}/metrics/deltaTree/response-fields.adoc[]

===== Example Request

[NOTE]
=====
This request can be sent using either the GET or the POST method. See <<usage-of-get, Usage of GET>>.
=====
include::{snippets}/metrics/deltaTree/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/deltaTree/http-response.adoc[]

=== Files

==== Querying the file tree of a particular commit.

===== Response Structure

include::{snippets}/files/tree/response-fields.adoc[]

===== Example Request

include::{snippets}/files/tree/http-request.adoc[]

===== Example Response

include::{snippets}/files/tree/http-response.adoc[]

== Contributors

=== Structure

include::{snippets}/contributors/get/response-fields.adoc[]

=== List all contributors of a project

[discrete]
==== Example Request

include::{snippets}/contributors/list/http-request.adoc[]

[discrete]
==== Example Response

include::{snippets}/contributors/list/http-response.adoc[]

[discrete]
==== Response Structure

include::{snippets}/contributors/list/response-fields.adoc[]



=== List all contributors for a given path

[discrete]
==== Example Request for a File

include::{snippets}/contributors/list/path/file/http-request.adoc[]

[discrete]
==== Example Response

include::{snippets}/contributors/list/path/file/http-response.adoc[]

[discrete]
==== Example Request for a Directory

include::{snippets}/contributors/list/path/directory/http-request.adoc[]

[discrete]
==== Example Response

include::{snippets}/contributors/list/path/directory/http-response.adoc[]



=== Get single contributor

[discrete]
==== Example request

include::{snippets}/contributors/get/http-request.adoc[]

[discrete]
==== Example response

include::{snippets}/contributors/get/http-response.adoc[]



=== Merge contributors

[discrete]
==== Request Structure

include::{snippets}/contributors/merge/request-fields.adoc[]

[discrete]
==== Example Request

include::{snippets}/contributors/merge/http-request.adoc[]

[discrete]
==== Example Response

include::{snippets}/contributors/merge/http-response.adoc[]



=== Update a Contributor

[discrete]
==== Request Structure

include::{snippets}/contributors/update/request-fields.adoc[]

[discrete]
==== Example Request

include::{snippets}/contributors/update/http-request.adoc[]

[discrete]
==== Example Response

include::{snippets}/contributors/update/http-response.adoc[]




== Coderadar Core Metrics

=== Get Critical Files of a Project

==== Files With Many Contributors

===== Request Structure

include::{snippets}/metrics/criticalFiles/numberOfContributors/request-fields.adoc[]

===== Example Request

include::{snippets}/metrics/criticalFiles/numberOfContributors/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/criticalFiles/numberOfContributors/http-response.adoc[]


==== Frequently Changed Files

===== Request Structure

include::{snippets}/metrics/criticalFiles/modificationFrequency/request-fields.adoc[]

===== Example Request

include::{snippets}/metrics/criticalFiles/modificationFrequency/http-request.adoc[]

===== Example Response

include::{snippets}/metrics/criticalFiles/modificationFrequency/http-response.adoc[]
